### ISSUE TITLE
Compatibility with pipewire

### ISSUE THREAD

**Issue by jose1711** [hastinbe/i3-volume#29]
Currently `i3-volume` became incompatible with distributions that switched from Pulseaudio to Pipewire as `pacmd` is removed during the migration. Not sure what options are there to bring it back.

**Comment by hastinbe** [comment]
You can install the `pulseaudio-utils` package to get those commands back. From my understanding they should continue to work with `pipewire`, if not you might need the `pipewire-pulse` package (`pipewire-pulseaudio` for fedora). Then `i3-volume` should continue to work using those commands.

Did the migration install `wireplumber`?

**Comment by jose1711** [comment]
Currently there's no `pulseaudio-utils` for Arch Linux (and by checking `pacman.log` there never was one - probably it was all part of `pulseaudio` package)

```
$ yay pulseaudio-utils
no packages match search
```

`wireplumber` was *not* installed during `pulseaudio` -> `pipewire` switch.

**Comment by hastinbe** [comment]
It looks most of the commands on Arch were provided by `libpulse`, except `pacmd` which was part of `pulseaudio`, and since `pulseaudio` now conflicts with `pipewire-pulse` the `pacmd` is missing. I'll replace `pacmd` with `pactl` soon as I have some time, that'll work for everyone until I can try `pipewire` and get its own CLI tools supported

**Comment by hastinbe** [comment]
Go ahead and pull from master or download https://github.com/hastinbe/i3-volume/releases/tag/v3.6.0

**Comment by jose1711** [comment]
Thank you for fixing on such a short notice!
