### ISSUE TITLE
amixer: Unable to find simple control 'Master',0

### ISSUE THREAD

**Issue by Nikolay1998** [hastinbe/i3-volume#37]
Not working. Sound card essx8336. ALSA.
amixer: Unable to find simple control 'Master',0

**Comment by hastinbe** [comment]
This happens if the control name `Master` doesn't exist on your system. This control name is just the default setting in i3-volume as it is the most common name found on most systems. Use the command `amixer scontrols` to find your correct mixer control. The name is within single quotations. Once you have the name, you can set it with the `-m` option of the `volume` script. 

Example settings for i3wm configuration if the your mixer control name was "Speaker" instead of "Master":

```
# Mixer control name
set $alsamixer Speaker

bindsym XF86AudioRaiseVolume exec --no-startup-id $volumepath/volume -an -t $statuscmd -u $statussig -m $alsamixer up $volumestep
bindsym XF86AudioLowerVolume exec --no-startup-id $volumepath/volume -an -t $statuscmd -u $statussig -m $alsamixer down $volumestep
bindsym XF86AudioMute        exec --no-startup-id $volumepath/volume -an -t $statuscmd -u $statussig -m $alsamixer mute
```
