### ISSUE TITLE
Does not actually change volume until approx. 10 minutes in

### ISSUE THREAD

**Issue by def14nt** [hastinbe/i3-volume#6]
I'm leaving this product.

**Comment by def14nt** [comment]
@hastinbe I was expecting a solution. And questions.

**Comment by ivanhercaz** [comment]
Solutions for what problem @def14nt? You only write a issue with a title that confuses and a description without an explanation of your problem or the bug found, nor error log. How could @hastinbe or anyone help you to solve your problem?

**Comment by def14nt** [comment]
these are the things i use
+ opensuse leap 15
+ chrome
+ i3 (duh)
+ intel core i7
+ gtx 1060
+ builtin sound card
+ pulseaudio

**Comment by def14nt** [comment]
I don't need this fixed though, I'm using a more stable diy product now with `bindsym XF86*` and `amixer`.

**Comment by ivanhercaz** [comment]
I still don't understand your issue :/

**Comment by hastinbe** [comment]
Hello. I closed the issue because it contained only a statement that you wouldn't use the product. I'm glad you found a solution to your problem. i3-volume can control your volume using either pulseaudio-utils or alsa-utils (amixer). The README provides information on how to switch to alsa-utils, as it seems that has resolved the problem for you. Otherwise, you would have to troubleshoot the issue with PulseAudio since i3-volume does not control your volume directly or have any code which could cause the behavior description in the title.

**Comment by def14nt** [comment]
@ivanhercaz Then don't comment.
